package player;

public class ParserException extends Exception {
	
	private static final long serialVersionUID = -391484377137870342L; // unique id generated by eclipse to serialize object
	
	public ParserException() { super(); }
	public ParserException(String message) { super(message); }
	public ParserException(String message, Throwable cause) { super(message, cause); }
	public ParserException(Throwable cause) { super(cause); }
}

